### ISSUE TITLE
Create a codemod for the `<Button />` component

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/codemod#31]
#### Problem statement

Recently we added a `<Button />` [component](https://github.com/sourcegraph/sourcegraph/blob/main/client/wildcard/src/components/Button/Button.tsx) to our component library — [the Wildcard package](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard). The codebase still mostly uses `<button class="btn-primary" />` instead of `<Button variant="primary" />` [in most places](https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+%3Cbutton+lang:typescript+&patternType=literal). We need to migrate to a new React component from the combination of the HTML element and CSS classes. This can be done with a help of the codemod that replace `<button />` with `<Button />` and relies on the React component API instead of CSS classes.

#### Success criteria

The codemod is written that:
1. Replaces `<button />` with `<Button />`.
2. Replaces CSS classes with matching React props like: `className="btn-primary"` -> `variant="primary"`.
3. Preserves all the other props and passes them to the `<Button />` component.
3. Adds `import { Button } from '@sourcegraph/wildcard'` if it's missing in the target source file.

#### Things to learn/practice during the implementation

1. How to write a codemod using [TS-morth](https://ts-morph.com/).
2. How to test and debug codemod.

#### Estimated amount of work

T-shirt size abstract estimate: **L**.

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue. Please explain to me in simple terms what needs to be done. There are 4 steps written that need to be done, should I just work on them individually? or do I have to create a file and do something else?!

**Comment by valerybugakov** [comment]
Closed by https://github.com/sourcegraph/codemod/pull/71
